### ISSUE TITLE
vox activation not working

### ISSUE THREAD

**Issue by jnoortheen** [anki-code/xontrib-back2dir#1]
This xontrib is useful with terminals like `kitty` which don't remember the last session. But when this xontrib is loaded, my custom script to activate the vox environment based on the current location is not getting fired. I suspect it is because the `events.on_cd` is not fired.

**Comment by anki-code** [comment]
Hi @jnoortheen! Thank you for reporting this!
Is there a way to repeat this (with description of expected and got behavior)?
But if you already have a fix PRs are very welcome!

**Comment by jnoortheen** [comment]
Yes you could use the `autovox`'s hooks and check if that works after enabling this xontrib.

Also I have a fix, I will create a PR.
